language: node_js
node_js:
  - '10'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: QIQ3jouWzcvA29Pj+qaaqoGImHX1ARK4kQgARx5eoRKGwZiRUtqMrtgxbMQpN33T+il2hod+sZUsogg/u8Gdpt0U01YgDkKPWvW6n9u1YD76+vy/4cNU3KNBb4dq5l3gf/7s7Z6/73AZiTJrbzqDX7Qzeq68V97wdXMwjFYyBCTD6LQer62XRKBYgZw7+qBk8jRHUeVoJQKtyb1vLXXvwmmi6fJaTcjj69PBYpitfsr0DsIymSuR2vIiAcuRgP28mquA3Hd8kJTsSStVPqXRKW3RJsdTJZgbwGdoklI4SA2lqqWacwjqdCiC2lTIX4eKiwNRS98gabltkwMmBJeX/Vfqmjdb1bjSCBVemaSabbNCsmBmspGRd6Tf9Knc4D8Q9sDEK4r1Ko2jrn/qgHzERT46b5M3/lZWBlNOf+x1HnyanQKNyUMDRa79Xehr82dXdCbMiiR4C/TX7iZi2LAEah4lu70THllvTAZ5sFrteC4M/Fowr32wGWqKrxu01EvS4083stMFrj7/9HDP+EVa4G48Mgbr2ylhlfvGJQ0pZp8sx2CFUxtJdreHmzLehL2njUYoEmzxHjdQtzNyxftH/VsFH5mG6l+06ohmb+0gq10cHUM5ERLJGevZkgNA9IIffvPW/jDwmIHu/11F+5QInMpreQVE8BabESJT48tYx7s=
  app: recipereportapi
  on:
    repo: nothingworksright/recipereport_api
