language: node_js
node_js:
  - "6"
branches:
  only:
  - master
deploy:
  provider: heroku
  app:
    master: grocereportapi
  strategy: api
  api_key:
     secure: SsWLWVosd/hQE4aOC6qL2oFJ6Zb6ok4PXoTfn6P20n1M/xP7rx4KK+SPo8xo7P/WJjHBlycjZJTNw2qxNzeLjnFe0cla38LN+4yzMTv7MK4ZGfywLVuRKxtW3TAldwMMI0KgAD3VGAiMy86RbX1FfzMLwUEfUYSrOzIzo66bCHKtlDEgNkpQzv7vcBiFE5B+zVmL9cXuRNFpMhb5lEvGbPautgajbU75Etv+B51embS6o5IfrgWEyBs27Y/tw8la6kkmfFFS+fFdgv6I7N+VYeKqm41jfKEV3eIesGtmhANuy3IZok3dlHs1ag3OYcNl7JDy1//t0v9vToKW8t4tq/bkbV3F0nl00JBS+dz0db0s9ZNOS5qjMkzcZu4FwXoJzUdLoTmOTCscmamXySO20d1pM4LNk6O3D5o3HO3+VZkHU5T14fOzkWfXFYaYr9WjX8d/Eo0VTdf+LOm6haf/bA8IwGB9EkzMrkGuyt+/Pzk4ZBaXe07cKDl0ovGvwJGp/Dv9vqWSHcj6s8gYNyid15MlI/8AgZmzUMS3uUzHi3zsadyFnynisKFT8aysDomQGPL1z5ZUdOn3dlQnNXyLKrsp/nxWE25NEcRrxTBhiSOUvtICddKmh0afT46SX2ezFBQ8mXtVQG5EprZnWxGH71aG/0BZn2xj8UKQRnvYenc=