language: node_js
node_js:
  - "6"
branches:
  only:
  - master
deploy:
  provider: heroku
  app:
    master: grocereportapi
  strategy: api
  api_key:
     secure: "XzVbhjGquAUfOFMGbgjnjL4vw+ZnsU71ImJOzd4IuWnAXAzqbsua8dHn9yB4angRRXIaaCm3mOZb/at/++Rc7Gu3l0/WY71ebIKaVQlBIMwJcLZUJ066odK4qJYMN15RW7DOV1ESeO7Fb5mrBeDHodG91OlOvZfttSRdmiHTSPOMqLhFTOYL5gWtEMLuf/47k4mxdmKQ5jzfZrSx46DiaOzmM4qW9bcUgSnnaobuk7wkv4A+T/VNdH0zX78Ns3DODXbwDszcoAW/0f9KgS+UZHmRaEQylG1yKEFpGqAN/oEjc+E6R67i/oKN/yY5+jNHE02DnFbL3DLeWKgKtTcdY16Fci7aSW/9vzHvf/4WYh0CI2VEUxHexhiPg65yxw/C/cV97bavMV2w9/vYwx3+nGoucsiys2TvbU8kCZ9jF9lTqzrnfChQs2IWsCVUbElqsVD1T3vbT5/u3gyJykawCkzrOZXi2OOJY72itrTRIM0uDp3HXvTmD7hFluc7DKva0aWPBCGA0DfbSegjhwSr6V1sMM8BYQNb5vhkgbwwuEBE6aCpEbt8HihVMqPbgwOAg2p2cAkKtty/UUiEjI6FAtJvUDKXPSkv/VML+VB5ZWi1ZQ9Kl8cLfU7SzKEdTjKLH4ZIND4X9dfhK63HdsuXz+wOTg5dhsghV598iug/5wk="
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5a961246e7d6d9693309 # https://gitter.im/nothingworksright/Lobby
      - https://webhooks.gitter.im/e/1de5b5d08268f586998f # https://gitter.im/nothingworksright/grocereport_api
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always
addons:
    code_climate:
        repo_token: 84291b1e539c5818a7813aa2cb1c6ab77a1baab8fec3ea1c5715862515148ccf