language: node_js
node_js:
  - "6"
branches:
  only:
  - master
deploy:
  provider: heroku
  app:
    master: grocereportapi
  strategy: api
  api_key:
    secure: "Aymhtx5GaGGsSPwjQQCVDNdeu7Ci+fPXLp9NEXgKqgk101Xh0bmLcj8w7YA+QJkBFS7i7TfZx+sOusIeYTwnGwzt/bWARAphotW1s5qt1j5L3qN80iAtReqIFwwMOiOw3cZBEAWCbsY7eJCw6Z5kcStQX7JvKWCi00+HcZWsVLVxSub5Nt43dE3Niuqit7xbAYW/nqZeq1neG3lFuUeh0ukBeFu6c8mtkULytpcKrOTUQ08T+wbX39hFdsAJOu22UO7+CBKgZSykMsqFRA1cSjn4VIBM1Ktq+vBhqMpy62fnXdsygtSis/4YWBQBHUWIVXsbOeIV6pweGMOZmcm5BOsek+darJW3e4alu0FwrrcFV+MuSCWP5B93UlyXRckYgGYWakwPxLCU2rwZ1WpFwnh4WrAljJ5qQXeosyMHH6FGPvqHGjvXwh/bbFK1dWYpJk8wNXfF3sDn5qytF/kjg17RtqS99h/CEqQnvim0+rM+Wfapy1PP1tCCOrI58G48C2uOUXnR54/kXpEziCeWvxckQtOlkIKoKZZ7jH6gXI36rvEABU+qQse0a/dGV+zKkDaM/Wtq8ItA4ieCp+9hjiIpKBcg+jSAWxcEKuR5+H2WItdhJ9YFhdoqFiSn9rphQ9b1fAsUL30UI0HANgjBBEX4NLGzpOErEpxZMqXRpwc="
