language: node_js
node_js:
  - "6"
branches:
  only:
  - master
deploy:
  provider: heroku
  app:
    master: grocereportapi
  strategy: api
  api_key:
    secure: 02bd9fbb-8088-4622-985f-caf578468a74