fixes:
  - "/home/runner/work/api.recipe.report/api.recipe.report::"
comment:
  layout: "reach, diff, flags, files, footer, sunburst"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no