name: Build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      NODE_ENV: development
      RR_PORT: 1138
      RR_CRYPTO_KEY: MqSm0P5dMgFSZhEBKpCv4dVKgDrsgrmT
      RR_CRYPTO_ALGO: aes-256-cbc
      RR_CRYPTO_IV_LENGTH: 16
      RR_JWT_SECRET: devTestEnvironment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.13.1

    - name: Install
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test

    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        verbose: true