name: Running Code Coverage

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.6

    - name: Install dependencies
      run: yarn install

    - name: Generate coverage report
      run: yarn run testonly

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2