name: Build-frontend

on:
  pull_request:
    types: [opened]
    branches:
      - main
    paths:
      - 'packages/web/**'
      - 'packages/data/**'
      - 'packages/domain/**'
      - 'packages/service/**'

jobs:
  build-frontend:

    runs-on: ubuntu-latest

    env:
      NODE_ENV: development

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.14.0

    - name: Install
      run: npm install

    - name: Build-Frontend
      run: npm run build
      working-directory: packages/web
