name: Deploy-frontend

on:
  push:
    branches:
      - main
    paths:
      - 'packages/web/**'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy-Frontend-Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script_stop: true
        script: |
          cd ~/recipe-report
          git pull
          npm install
          cd packages/web
          npm run build
