name: Build-React-App

on:
  pull_request:
    types: [opened]
    branches:
      - main
    paths:
      - 'packages/react-app/**'
      - 'packages/data/**'
      - 'packages/domain/**'
      - 'packages/service/**'

jobs:
  build-react-app:

    runs-on: ubuntu-latest

    env:
      NODE_ENV: development

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.17.0

    - name: Install
      run: npm install

    - name: Build-React-App
      run: npm run build
      working-directory: packages/react-app
