name: Deploy-staging

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'

jobs:
  deploy-staging:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy-Staging
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script_stop: true
        script: |
          cd ~/recipe-report
          git stash
          git pull
          npm install
          pm2 stop api.recipe.report
          cd ~/recipe-report/packages/api
          npm run build
          pm2 restart api.recipe.report
          cd ~/recipe-report/packages/web
          npm run build